# Generated by Django 3.1.4 on 2020-12-25 13:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower_id=django.db.models.expressions.F('following_id')), name='follower_id_and_following_id_can_not_be_equal'),
        ),
    ]
