# Generated by Django 3.1.4 on 2020-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201225_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='Name', max_length=255),
        ),
    ]
