# Generated by Django 3.1.4 on 2020-12-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_posts', to='network.post'),
        ),
    ]
