# Generated by Django 3.1.4 on 2020-12-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201226_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following_posts',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL), to='network.Post'),
        ),
    ]
