# Generated by Django 3.1.4 on 2020-12-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follow_following_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following_posts',
        ),
    ]
