# Generated by Django 3.1.4 on 2020-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_follow_following_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following_posts',
            field=models.ManyToManyField(to='network.Post'),
        ),
    ]
